import React,{useEffect,useRef,useState}from'react';
import{io}from'socket.io-client';

const API_ORIGIN=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const SOCKET_ORIGIN=(import.meta.env.VITE_SOCKET_URL||API_ORIGIN||window.location.origin).replace(/\/$/,'');
const readSession=()=>{try{return JSON.parse(localStorage.getItem('session')||'null')}catch{return null}};
const api=(path,options={})=>fetch(API_ORIGIN+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}).then(async response=>{const isJson=(response.headers.get('content-type')||'').includes('application/json');const data=isJson?await response.json().catch(()=>({})):{};if(!response.ok||!isJson)throw Error(data.error||'The Social Chat API is not connected yet.');return data});

export default function App(){
 const[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[session,setSession]=useState(readSession),[messages,setMessages]=useState([]),[text,setText]=useState(''),[error,setError]=useState('');
 const socketRef=useRef(null);
 useEffect(()=>{if(!session){socketRef.current?.disconnect();socketRef.current=null;return}let active=true;setError('');api('/api/messages',{headers:{Authorization:'Bearer '+session.token}}).then(items=>{if(active)setMessages(Array.isArray(items)?items:[])}).catch(e=>{if(active){setError(e.message);if(e.message==='Please log in'){localStorage.removeItem('session');setSession(null)}}});const socket=io(SOCKET_ORIGIN,{auth:{token:session.token},transports:['websocket','polling']});socketRef.current=socket;socket.on('message:new',message=>setMessages(value=>value.some(item=>item.id===message.id)?value:[...value,message]));socket.on('connect_error',()=>setError('Live chat connection failed. Please try again.'));return()=>{active=false;socket.disconnect();if(socketRef.current===socket)socketRef.current=null}},[session]);
 async function submit(event){event.preventDefault();setError('');try{const data=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('session',JSON.stringify(data));setMessages([]);setSession(data);setError('')}catch(e){setError(e.message)}}
 function send(event){event.preventDefault();const value=text.trim(),socket=socketRef.current;if(!value)return;if(!socket?.connected){setError('Live chat is not connected yet. Please try again in a moment.');return}socket.emit('message:send',value);setText('')}
 function logout(){socketRef.current?.disconnect();localStorage.removeItem('session');setSession(null);setMessages([]);setError('')}
 if(!session)return <main className="auth"><section className="auth-card"><p className="eyebrow">Social Media & Chat</p><h1>Connect with your people.</h1><p className="muted">A React, Express, JWT, and Socket.io portfolio project.</p><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Log in</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Create account</button></div><form onSubmit={submit}>{mode==='register'&&<input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength="6" required/><button className="primary">{mode==='login'?'Log in':'Create account'}</button></form>{error&&<p className="error">{error}</p>}</section></main>;
 return <main className="chat"><header><div><p className="eyebrow">Social Media & Chat Application</p><h1>Community room</h1></div><button className="logout" onClick={logout}>Log out</button></header><section className="room"><div className="messages">{messages.length?messages.map(message=><article key={message.id} className={message.userId===session.user.id?'mine':''}><strong>{message.name}</strong><p>{message.text}</p><small>{new Date(message.createdAt).toLocaleTimeString()}</small></article>):<p className="muted">No messages yet. Say hello.</p>}</div>{error&&<p className="error">{error}</p>}<form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message..."/><button className="primary">Send</button></form></section></main>
}
